// ============================================================
// AUTO-GENERATED ESP32 / OPENCAT DOG MOTION TABLE PLAYER
// ============================================================
//
// Generated by dog_motion_designer_generate_cpp.py
//
// This file contains ONLY the motions selected in the simulator.
//
// Serial commands:
//   Send the listed number to play the corresponding motion.
//
// IMPORTANT:
//   Verify servo indexes for your Bittle/OpenCat robot.
//
// ============================================================

#include <WiFi.h>

// ============================================================
// WIFI COMMAND SETTINGS
// ============================================================
// Replace these with your Wi-Fi router credentials.
const char* WIFI_SSID     = "YOUR_WIFI_NAME";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// TCP command port.
// Example PC command:
//   echo walk | nc <ESP32_IP_ADDRESS> 8888
WiFiServer wifiServer(8888);

#define FL_HIP   0
#define FL_KNEE  1
#define FR_HIP   2
#define FR_KNEE  3
#define RL_HIP   4
#define RL_KNEE  5
#define RR_HIP   6
#define RR_KNEE  7

#define STEP_DELAY_MS 250

struct MotionTable {
  const char* name;
  const int (*rows)[8];
  int rowCount;
  int repeatCount;
};

void writeServoAngle(int servoIndex, int angle) {
  // ----------------------------------------------------------
  // Replace this body if your OpenCat firmware uses a different
  // servo-write function.
  // ----------------------------------------------------------
#ifdef ESP_PWM
  servo[servoIndex].write(angle);
#else
  pwm.writeAngle(servoIndex, angle);
#endif
}

void applyMotionRow(const int row[8]) {
  writeServoAngle(FL_HIP,  row[0]);
  writeServoAngle(FL_KNEE, row[1]);
  writeServoAngle(FR_HIP,  row[2]);
  writeServoAngle(FR_KNEE, row[3]);
  writeServoAngle(RL_HIP,  row[4]);
  writeServoAngle(RL_KNEE, row[5]);
  writeServoAngle(RR_HIP,  row[6]);
  writeServoAngle(RR_KNEE, row[7]);
}

// ============================================================
// MOTION - Stand
// ============================================================
const int MOTION_STAND[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
};

// ============================================================
// MOTION - Jump
// ============================================================
const int MOTION_JUMP[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
  { 90       120       90       120       90       120       90       120      },
  { 90       135       90       135       90       135       90       135      },
  { 90       80        90       80        90       80        90       80       },
  { 90       70        90       70        90       70        90       70       },
  { 90       120       90       120       90       120       90       120      },
  { 90       90        90       90        90       90        90       90       },
};

// ============================================================
// MOTION - Turn Right
// ============================================================
const int MOTION_TURN_RIGHT[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
  { 120      120       60       90        120      120       60       90       },
  { 120      90        60       90        120      90        60       90       },
  { 60       90        120      120       60       90        120      120      },
  { 60       90        120      90        60       90        120      90       },
  { 90       90        90       90        90       90        90       90       },
};

// ============================================================
// MOTION - Turn Left
// ============================================================
const int MOTION_TURN_LEFT[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
  { 60       90        120      120       60       90        120      120      },
  { 60       90        120      90        60       90        120      90       },
  { 120      120       60       90        120      120       60       90       },
  { 120      90        60       90        120      90        60       90       },
  { 90       90        90       90        90       90        90       90       },
};

// ============================================================
// MOTION - Sit
// ============================================================
const int MOTION_SIT[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
  { 90       90        90       90        80       115       80       115      },
  { 90       90        90       90        70       130       70       130      },
  { 90       90        90       90        60       140       60       140      },
};

// ============================================================
// MOTION - Walk
// ============================================================
const int MOTION_WALK[][8] = {
  // -------------------------------------------------------------------------
// FL_HIP  FL_KNEE  FR_HIP  FR_KNEE  RL_HIP  RL_KNEE  RR_HIP  RR_KNEE
  // -------------------------------------------------------------------------
  { 90       90        90       90        90       90        90       90       },
  { 120      120       90       90        90       90        90       90       },
  { 120      90        90       90        90       90        90       90       },
  { 60       90        90       90        60       90        90       90       },
  { 90       90        120      120       90       90        90       90       },
  { 90       90        120      90        90       90        90       90       },
  { 90       90        60       90        90       90        60       90       },
  { 90       90        90       90        120      120       90       90       },
  { 90       90        90       90        120      90        90       90       },
  { 60       90        90       90        60       90        90       90       },
  { 90       90        90       90        90       90        120      120      },
  { 90       90        90       90        90       90        120      90       },
  { 90       90        60       90        90       90        60       90       },
  { 90       90        90       90        90       90        90       90       },
};

// ============================================================
// SELECTED MOTION REGISTRY
// ============================================================
MotionTable motions[] = {
  {"stand", MOTION_STAND, sizeof(MOTION_STAND) / sizeof(MOTION_STAND[0]), 1},
  {"jump", MOTION_JUMP, sizeof(MOTION_JUMP) / sizeof(MOTION_JUMP[0]), 1},
  {"turn_right", MOTION_TURN_RIGHT, sizeof(MOTION_TURN_RIGHT) / sizeof(MOTION_TURN_RIGHT[0]), 3},
  {"turn_left", MOTION_TURN_LEFT, sizeof(MOTION_TURN_LEFT) / sizeof(MOTION_TURN_LEFT[0]), 3},
  {"sit", MOTION_SIT, sizeof(MOTION_SIT) / sizeof(MOTION_SIT[0]), 1},
  {"walk", MOTION_WALK, sizeof(MOTION_WALK) / sizeof(MOTION_WALK[0]), 3},
};

const int MOTION_COUNT = sizeof(motions) / sizeof(motions[0]);

void playMotion(int motionIndex) {
  if (motionIndex < 0 || motionIndex >= MOTION_COUNT) {
    Serial.println("ERROR: invalid motion index");
    return;
  }

  MotionTable motion = motions[motionIndex];
  Serial.print("Playing motion: ");
  Serial.println(motion.name);

  for (int r = 0; r < motion.repeatCount; r++) {
    for (int i = 0; i < motion.rowCount; i++) {
      applyMotionRow(motion.rows[i]);
      delay(STEP_DELAY_MS);
    }
  }
}

int findMotionByName(String command) {
  command.trim();
  command.toLowerCase();

  for (int i = 0; i < MOTION_COUNT; i++) {
    String motionName = String(motions[i].name);
    motionName.toLowerCase();

    if (command == motionName) {
      return i;
    }
  }

  return -1;
}

void printHelp() {
  Serial.println();
  Serial.println("======================================");
  Serial.println(" GENERATED DOG MOTION PLAYER");
  Serial.println("======================================");
  Serial.println("Send one of these text commands:");
  Serial.println("  stand");
  Serial.println("  jump");
  Serial.println("  turn_right");
  Serial.println("  turn_left");
  Serial.println("  sit");
  Serial.println("  walk");
  Serial.println("");
  Serial.println("Other commands:");
  Serial.println("  help");
  Serial.println("======================================");
}

void handleCommand(String command) {
  command.trim();
  command.toLowerCase();

  if (command.length() == 0) {
    return;
  }

  if (command == "help" || command == "h") {
    printHelp();
    return;
  }

  int motionIndex = findMotionByName(command);

  if (motionIndex >= 0) {
    playMotion(motionIndex);
    Serial.println("OK");
  }
  else {
    Serial.print("ERROR: unknown command: ");
    Serial.println(command);
    printHelp();
  }
}

void startWiFiCommandServer() {
  Serial.println("Starting Wi-Fi command server...");

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  Serial.print("Connecting to Wi-Fi");

  int retryCount = 0;
  while (WiFi.status() != WL_CONNECTED && retryCount < 40) {
    delay(500);
    Serial.print(".");
    retryCount++;
  }

  Serial.println();

  if (WiFi.status() == WL_CONNECTED) {
    Serial.print("ESP32 IP Address: ");
    Serial.println(WiFi.localIP());
    wifiServer.begin();
    Serial.println("Wi-Fi TCP command server started on port 8888");
  }
  else {
    Serial.println("Wi-Fi connection failed. USB Serial commands still work.");
  }
}

bool handleUsbSerialCommand() {
  if (!Serial.available()) {
    return false;
  }

  String command = Serial.readStringUntil('\n');
  Serial.print("USB command received: ");
  Serial.println(command);
  handleCommand(command);
  return true;
}

bool handleWiFiCommand() {
  if (WiFi.status() != WL_CONNECTED) {
    return false;
  }

  WiFiClient client = wifiServer.available();

  if (!client) {
    return false;
  }

  String command = client.readStringUntil('\n');
  command.trim();

  Serial.print("Wi-Fi command received: ");
  Serial.println(command);

  handleCommand(command);

  client.println("OK: command received");
  client.stop();

  return true;
}

void setup() {
  Serial.begin(115200);
  delay(1000);

  printHelp();
  startWiFiCommandServer();

  // Start in the first selected motion once.
  playMotion(0);
}

void loop() {
  // ----------------------------------------------------------
  // Priority rule:
  // 1. If USB Serial command is available, use USB command.
  // 2. If no USB command is available, check Wi-Fi TCP command.
  // ----------------------------------------------------------

  if (handleUsbSerialCommand()) {
    return;
  }

  handleWiFiCommand();
}
